export const usaState = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const days = [
  { id: 0, day: "Sun", from:"", to:"", checked:false },
  { id: 1, day: "Mon", from:"", to:"", checked:false },
  { id: 2, day: "Tue", from:"", to:"", checked:false },
  { id: 3, day: "Wed", from:"", to:"", checked:false },
  { id: 4, day: "Thr", from:"", to:"", checked:false },
  { id: 5, day: "Fri", from:"", to:"", checked:false },
  { id: 6, day: "Sat", from:"", to:"", checked:false },
];
